# This file corresponds to the `rust-toolchain` file used in `ink_linting` here:
# https://github.com/paritytech/ink/blob/1c029a153ead15cd0bd76631613967c9e679e0c1/linting/rust-toolchain.toml#L5
#
# The `ink_linting` lints are integrated into each contract's manifest file and
# compiled for each project. We need this file here to build the entire project
# using the same toolchain, thereby simplifying the installation process.

[toolchain]
channel = "nightly-2023-12-28"
components = ["llvm-tools-preview", "rustc-dev"]
